### ISSUE TITLE
add sub-title to pdf bookmarks

### ISSUE THREAD

**Issue by WanderMax** [LenKiMo/byte-of-python#16]
I suggest to add sub-title to pdf bookmarks.
The current on only has the main title in bookmark.
Thanks

**Comment by LenKiMo** [comment]
The PDF is created and compiled automatically by GitBook, I can't control how they generate.
You can consider send your advise to GitBook to improve their program on this aspect.
For the moment and for the foreseeable future, PDF version will still provided by GitBook automatically, due to the Book still need emended. 
Therefore, for now there is not much thing I can do, sorry about that.

**Comment by WanderMax** [comment]
thanks
